Vagrant.configure("2") do |config|

  path = 'provisioner/apps/'

  config.vm.provision 'Applications',
    type:                 :ansible_local,
    install:              false,
    playbook:             path + 'Playbook.yml',
    galaxy_role_file:     path + 'Requirements.yml',
    galaxy_command:       'ansible-galaxy install \
                              --role-file=%{role_file} \
                              --roles-path=%{roles_path}'

  config.vm.provision :reload

end
