Vagrant.configure("2") do |config|

  path = 'provisioner/startup/'

  config.vm.provision 'Startup - Install requirements',
    type:                 :shell,
    path:                 path + 'Requirements.sh'

  config.vm.provision 'Startup - Install ansible_local',
    type:                 :ansible_local,
    install_mode:         :pip,
    playbook:             path + 'Playbook.yml'

  config.vm.provision :reload

end
