Vagrant.configure("2") do |config|

  path = 'provisioner/security/'

  config.ssh.private_key_path   = path + 'id_rsa'
  config.ssh.insert_key         = false
  config.ssh.keys_only          = false

  config.vm.provision 'Security - SSH key pair',
    type:                 'file',
    source:               path + 'id_rsa.pub',
    destination:          '~/.ssh/authorized_keys'

  config.vm.provision 'Security - Users and groups',
    type:                 :ansible_local,
    install:              false,
    playbook:             path + 'Playbook.yml'

  config.vm.provision :reload

end
