Vagrant.configure('2') do |config|

  config.vm.define 'itaipu', autostart: false do |machine|

    machine.proxy.http      = ENV['HTTP_PROXY']
    machine.proxy.https     = ENV['HTTPS_PROXY']
    machine.proxy.no_proxy  = ENV['NO_PROXY']

  end

end
